In [1]:
import numpy as np
a = np.arange(3,10)  # 左闭右开
a

array([3, 4, 5, 6, 7, 8, 9])

In [3]:
a = [1,2,3]
b = a
b[0] = 2
a

[2, 2, 3]

In [4]:
a = 3
b = a
b = 1
a

3

In [10]:
import numpy as np
a = np.random.randn(7,3)
a

array([[-0.53278721, -1.97413337, -2.14444108],
       [-0.8099674 , -0.73818631,  0.18441867],
       [-0.14830113, -1.21240172, -0.22232941],
       [-0.32338494,  0.01929624,  0.28188794],
       [ 0.32130983,  0.55000626, -1.24017091],
       [ 0.47723648,  0.18030403,  0.36641377],
       [-0.34584399,  1.29055857, -0.38564518]])

In [11]:
a[1] = 1
a

array([[-0.53278721, -1.97413337, -2.14444108],
       [ 1.        ,  1.        ,  1.        ],
       [-0.14830113, -1.21240172, -0.22232941],
       [-0.32338494,  0.01929624,  0.28188794],
       [ 0.32130983,  0.55000626, -1.24017091],
       [ 0.47723648,  0.18030403,  0.36641377],
       [-0.34584399,  1.29055857, -0.38564518]])

In [12]:
a = np.random.randn(7)*5
a

array([ 4.56301162, -3.93108527, -5.28081486, -7.33359056,  1.58892893,
        4.15062351, -1.90211054])

In [13]:
np.modf(a)

(array([ 0.56301162, -0.93108527, -0.28081486, -0.33359056,  0.58892893,
         0.15062351, -0.90211054]), array([ 4., -3., -5., -7.,  1.,  4., -1.]))

In [30]:
a = np.ones((5,4))
a.cumsum(1)

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])